name: Annual Purge - Dry Run

on:
  schedule:
    - cron: "30 1 3 3 *" # 매년 3/3 01:30 UTC (한국 10:30) - 삭제 안 함
  workflow_dispatch: {} # 수동으로도 실행 가능

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Compute default fiscal range
        id: period
        run: |
          Y=$(date -u +%Y)
          echo "from=$((Y-1))-03-01" >> $GITHUB_OUTPUT
          echo "to=$Y-03-01" >> $GITHUB_OUTPUT

      - name: Provisions dry-run
        id: prov
        run: |
          curl -sS -X POST \
            "${{ secrets.PURGE_URL }}/admin/purge?collection=provisions&from=${{ steps.period.outputs.from }}&to=${{ steps.period.outputs.to }}&dryRun=true" \
            -H "X-CRON-SECRET: ${{ secrets.PURGE_CRON_SECRET }}" | tee prov.json

      - name: Visits dry-run
        id: vis
        run: |
          curl -sS -X POST \
            "${{ secrets.PURGE_URL }}/admin/purge?collection=visits&from=${{ steps.period.outputs.from }}&to=${{ steps.period.outputs.to }}&dryRun=true" \
            -H "X-CRON-SECRET: ${{ secrets.PURGE_CRON_SECRET }}" | tee vis.json

      - name: Upload dry-run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: purge-dryrun-${{ steps.period.outputs.from }}_${{ steps.period.outputs.to }}
          path: |
            prov.json
            vis.json

      - name: Post summary (no deletion performed)
        run: |
          echo "### Annual purge dry-run (no deletion)" >> $GITHUB_STEP_SUMMARY
          echo "- Range: **${{ steps.period.outputs.from }} ~ ${{ steps.period.outputs.to }}**" >> $GITHUB_STEP_SUMMARY
          echo "- See artifacts for counts. Run the **Manual Purge** workflow to delete." >> $GITHUB_STEP_SUMMARY
