name: Annual Purge - Manual Delete

on:
  workflow_dispatch:
    inputs:
      from:
        description: "시작(ISO, 예: 2024-03-01)"
        required: true
      to:
        description: "종료 미포함(ISO, 예: 2025-03-01)"
        required: true
      confirm:
        description: "안전문구 입력: DELETE-DATA"
        required: true

jobs:
  purge:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Export secrets to env
        run: |
          echo "PURGE_URL=${{ secrets.PURGE_URL }}" >> $GITHUB_ENV
          echo "PURGE_CRON_SECRET=${{ secrets.PURGE_CRON_SECRET }}" >> $GITHUB_ENV

      - name: Guard - confirmation phrase
        run: |
          if [ "${{ inputs.confirm }}" != "DELETE-DATA" ]; then
            echo "Type DELETE-DATA to proceed."; exit 1;
          fi

      - name: Purge provisions (hard delete)
        run: |
          curl -sS -X POST \
            "$PURGE_URL/admin/purge?collection=provisions&from=${{ inputs.from }}&to=${{ inputs.to }}&confirm=true" \
            -H "X-CRON-SECRET: $PURGE_CRON_SECRET"

      - name: Purge visits (hard delete)
        run: |
          curl -sS -X POST \
            "$PURGE_URL/admin/purge?collection=visits&from=${{ inputs.from }}&to=${{ inputs.to }}&confirm=true" \
            -H "X-CRON-SECRET: $PURGE_CRON_SECRET"

      - name: Post summary
        run: |
          echo "### Annual purge - manual delete" >> $GITHUB_STEP_SUMMARY
          echo "- Deleted range: **${{ inputs.from }} ~ ${{
            inputs.to }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Executed via GitHub Actions using cron secret." >> $GITHUB_STEP_SUMMARY
