name: Annual Purge - Dry Run

on:
  schedule:
    - cron: "30 1 3 3 *" # 매년 3/3 01:30 UTC (한국 10:30) - 삭제 없음
  workflow_dispatch: {} # 필요 시 수동 실행도 가능

jobs:
  dryrun:
    runs-on: ubuntu-latest

    steps:
      - name: Export secrets to env
        run: |
          echo "PURGE_URL=${{ secrets.PURGE_URL }}" >> $GITHUB_ENV
          echo "PURGE_CRON_SECRET=${{ secrets.PURGE_CRON_SECRET }}" >> $GITHUB_ENV

      - name: Compute default fiscal range (prev Mar 1 ~ this Mar 1)
        id: period
        run: |
          Y=$(date -u +%Y)
          FROM="$((Y-1))-03-01"
          TO="$Y-03-01"
          echo "from=$FROM" >> $GITHUB_OUTPUT
          echo "to=$TO" >> $GITHUB_OUTPUT

      - name: Provisions dry-run
        id: prov
        run: |
          curl -sS -X POST \
            "$PURGE_URL/admin/purge?collection=provisions&from=${{ steps.period.outputs.from }}&to=${{ steps.period.outputs.to }}&dryRun=true" \
            -H "X-CRON-SECRET: $PURGE_CRON_SECRET" | tee prov.json

      - name: Visits dry-run
        id: vis
        run: |
          curl -sS -X POST \
            "$PURGE_URL/admin/purge?collection=visits&from=${{ steps.period.outputs.from }}&to=${{ steps.period.outputs.to }}&dryRun=true" \
            -H "X-CRON-SECRET: $PURGE_CRON_SECRET" | tee vis.json

      - name: Upload dry-run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: purge-dryrun-${{ steps.period.outputs.from }}_${{ steps.period.outputs.to }}
          path: |
            prov.json
            vis.json

      - name: Post summary (no deletion performed)
        run: |
          echo "### Annual purge dry-run (no deletion)" >> $GITHUB_STEP_SUMMARY
          echo "- Range: **${{ steps.period.outputs.from }} ~ ${{ steps.period.outputs.to }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts contain counts for provisions/visits." >> $GITHUB_STEP_SUMMARY
          echo "- To actually delete, run the **Manual Delete** workflow with confirmation." >> $GITHUB_STEP_SUMMARY
